### ISSUE TITLE
[BUG]New version creates error when importing submodel

### ISSUE THREAD

**Issue by Bar3644** [eclipse-aaspe/package-explorer#245]
When a submodel is loaded as Auxiliary and is "Copy recursively" an error occurs. From the log:

Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: Value cannot be null. (Parameter 'source') Value cannot be null. (Parameter 'source') at    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Extensions.ExtendEnvironment.FindSubmodel(Environment environment, IReference submodelReference) in D:\a\package-explorer\package-explorer\src\AasxCsharpLibrary\Extensions\ExtendEnvironment.cs:line 500
   at Extensions.ExtendEnvironment.CopySubmodelRefAndCD(Environment environment, Environment srcEnv, IReference srcSubRef, Boolean copySubmodel, Boolean copyCD, Boolean shallowCopy) in D:\a\package-explorer\package-explorer\src\AasxCsharpLibrary\Extensions\ExtendEnvironment.cs:line 1057
   at AasxPackageLogic.DispEditHelperEntities.<>c__DisplayClass8_0.<DisplayOrEditAasEntityAas>b__6(Int32 buttonNdx, AasxMenuActionTicket ticket) in D:\a\package-explorer\package-explorer\src\AasxPackageLogic\DispEditHelperEntities.cs:line 1409
   at AasxPackageLogic.DispEditHelperBasics.<>c__DisplayClass21_2.<AddActionPanel>b__2(Object o) in D:\a\package-explorer\package-explorer\src\AasxPackageLogic\DispEditHelperBasics.cs:line 727
   at AnyUi.AnyUiDisplayContextWpf.<>c__DisplayClass25_8.<<InitRenderRecs>b__45>d.MoveNext() in D:\a\package-explorer\package-explorer\src\AasxWpfControlLibrary\AnyUiWpf.cs:line 1118
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).

** The same operation works with the previous version.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Build: 22631.4037

**Comment by BirgitBoss** [comment]
The auxiliary submodel can be loaded without problem as "normal" submodel?
Is it happening for any submodel you load as auxiliary or just a specific one?
